### ISSUE TITLE
Add RSS feed for the blog articles

### ISSUE THREAD

**Issue by dweidner** [oliverjam/oliverjames-v3#11]
I really like your blog articles, would you accept a pull request, that adds an RSS feed to your blog?

**Comment by oliverjam** [comment]
Thank you! I've been meaning to do this for ages, but got to the point of researching the difference between RSS and Atom and then got sidetracked. I assume it would be relatively simple using [the RSS plugin](https://github.com/11ty/eleventy-plugin-rss).

If you'd like to make a PR that would be amazing, if not I'll probably get round to it some time this weekend.
